# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MyBlog
email: muench.kaleb@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Hello, my name is Kaleb. 
 Currently I am a bachelor student of computer science 
 at the Hochschule für Technik in Stuttgart. 
 My experience mainly consists of Java programming, building apps with Android Studio 
 and some hobby tinkering with Arduino. 
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  KaMuench
author: "Kaleb Münch"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Collections:
collections:
  projects:
    output: true                                    # necessary for jekyll to generate output folder in _site and create html files for corresponding project files
    # custom_permalink_placeholders: ["subtitle"]     # add custom placeholder to permalink placeholders -> needs gem jekyll_custom_permalink', '~> 0.0'
    permalink: "/projects/:slugified_categories/:year-:month-:day_:slug.html"

#Defaults
defaults:
  - scope:
      path: "_projects"
    values:
      layout: "project"
      image_name: "info.png"
      image_info: "Image info"
  - scope:
      path: "_posts"
    values:
      author: "Kaleb Münch"


      
      


